[debug] [2023-01-19T16:14:33.459Z] ----------------------------------------------------------------------
[debug] [2023-01-19T16:14:33.461Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\abdo3\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js init
[debug] [2023-01-19T16:14:33.462Z] CLI Version:   11.20.0
[debug] [2023-01-19T16:14:33.462Z] Platform:      win32
[debug] [2023-01-19T16:14:33.462Z] Node Version:  v18.13.0
[debug] [2023-01-19T16:14:33.463Z] Time:          Thu Jan 19 2023 18:14:33 GMT+0200 (Eastern European Standard Time)
[debug] [2023-01-19T16:14:33.464Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-01-19T16:14:33.469Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2023-01-19T16:14:33.553Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-01-19T16:14:33.553Z] > authorizing via signed-in user (abdo3yash@gmail.com)
[info] 
     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  C:\work\clash\web

Before we get started, keep in mind:

  * You are currently outside your home directory

[debug] [2023-01-19T16:14:36.510Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2023-01-19T16:14:36.510Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[debug] [2023-01-19T16:14:59.045Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\abdo3\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:253:49)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
[error] 
[error] Error: An unexpected error has occurred.
